# Generated by Django 4.1.4 on 2023-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentatesoreriacontratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(default='No asignado', max_length=80, verbose_name='Nombre completo')),
                ('cedula', models.IntegerField(default=1, verbose_name='Cedula')),
                ('objetocontrato', models.CharField(default='No asignado', max_length=200, verbose_name='Objeto del contrato')),
                ('pdfplanilla', models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf de la planilla')),
                ('ordenpago', models.CharField(default='No', max_length=200, verbose_name='Orden de pago')),
                ('egreso', models.CharField(default='No', max_length=200, verbose_name='Numero comprobante de egreso')),
            ],
        ),
    ]
