# Generated by Django 4.1.4 on 2023-06-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='fechaactainicio',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='fechacontrato',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='fechaperfeccionamiento',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='fecharp',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='fechaterminacion',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='numeroactainicio',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='numerorp',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='objeto',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='observacionessupervisor',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='primerapellido',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='segundoapellido',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='segundonombre',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='tipodocumento',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='validacionsupervisor',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='valor',
        ),
        migrations.AddField(
            model_name='cuentasupervisor',
            name='nombrecompleto',
            field=models.CharField(default='No asignado', max_length=80, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='cuentasupervisor',
            name='objetocontrato',
            field=models.CharField(default='No asignado', max_length=200, verbose_name='Objeto del contrato'),
        ),
        migrations.AddField(
            model_name='cuentasupervisor',
            name='pdfcontrato',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf del contrato'),
        ),
        migrations.AddField(
            model_name='cuentasupervisor',
            name='pdfplanilla',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf de la planilla'),
        ),
        migrations.AlterField(
            model_name='cuentasupervisor',
            name='cedula',
            field=models.IntegerField(default=1, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='cuentasupervisor',
            name='radicado',
            field=models.CharField(default='No asignado', max_length=80, verbose_name='Radicado'),
        ),
    ]
