# Generated by Django 4.1.4 on 2023-06-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0002_remove_cuentasupervisor_dependencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentasupervisorcontratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecompleto', models.CharField(default='No asignado', max_length=80, verbose_name='Nombre completo')),
                ('cedula', models.IntegerField(default=1, verbose_name='Cedula')),
                ('objetocontrato', models.CharField(default='No asignado', max_length=200, verbose_name='Objeto del contrato')),
                ('radicado', models.CharField(default='No asignado', max_length=80, verbose_name='Radicado')),
                ('pdfcontrato', models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf del contrato')),
                ('pdfplanilla', models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf de la planilla')),
            ],
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='nombrecompleto',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='objetocontrato',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='pdfcontrato',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='pdfplanilla',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisor',
            name='radicado',
        ),
        migrations.AddField(
            model_name='cuentasupervisor',
            name='nombre',
            field=models.CharField(default='No asignado', max_length=40, verbose_name='Primer nombre'),
        ),
    ]
