# Generated by Django 4.1.4 on 2023-06-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0003_cuentasupervisorcontratista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentasupervisorcontratista',
            name='pdfcontrato',
        ),
        migrations.RemoveField(
            model_name='cuentasupervisorcontratista',
            name='radicado',
        ),
        migrations.AddField(
            model_name='cuentasupervisorcontratista',
            name='archivo',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf del formato de actividades'),
        ),
    ]
