# Generated by Django 4.1.4 on 2023-07-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0004_remove_cuentasupervisorcontratista_pdfcontrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisore',
            fields=[
                ('nombrecompleto', models.CharField(default='No asignado', max_length=120, verbose_name='Nombre completo')),
                ('cedula', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Cedula')),
                ('cargo', models.CharField(default='No asignado', max_length=120, verbose_name='Cargo')),
            ],
        ),
    ]
