# Generated by Django 4.1.4 on 2023-07-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0005_supervisore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supervisore',
            new_name='supervisor',
        ),
    ]
