# Generated by Django 5.0.3 on 2024-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0006_rename_supervisore_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='cargo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='nombrecompleto',
            field=models.CharField(max_length=120, verbose_name='Nombre completo'),
        ),
    ]
