# Generated by Django 5.0.3 on 2024-07-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0006_rename_supervisore_supervisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='supervisor',
        ),
    ]
