# Generated by Django 5.0.3 on 2024-09-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0007_alter_supervisor_cargo_alter_supervisor_cedula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='nombrecompleto',
        ),
        migrations.AddField(
            model_name='supervisor',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cédula'),
        ),
    ]
