# Generated by Django 5.0.3 on 2024-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudsistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundonombre', models.CharField(max_length=40, verbose_name='Segundo nombre')),
                ('primerapellido', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('segundoapellido', models.CharField(max_length=40, verbose_name='Segundo apellido')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('supervisor', models.CharField(default='', max_length=40, verbose_name='Supervisor')),
                ('tipodocumento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cedula de extranjeria')], default='CC', max_length=40, verbose_name='Tipo de documento')),
                ('cedula', models.IntegerField(max_length=40, verbose_name='Cedula')),
                ('lugarexpedicion', models.CharField(max_length=40, verbose_name='Lugar de expedicion')),
                ('dependencia', models.CharField(max_length=40, verbose_name='Dependencia')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=40, verbose_name='Sexo')),
                ('usuario', models.CharField(max_length=40, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=40, verbose_name='Contrasena')),
                ('telefono', models.CharField(default='', max_length=40, verbose_name='Telefono')),
                ('direccion', models.CharField(default='', max_length=40, verbose_name='Direccion')),
                ('sede', models.CharField(default='Administrativa', max_length=80, verbose_name='Sede')),
                ('fechafinalcontrato', models.CharField(default='', max_length=40, verbose_name='Fecha final del contrato')),
                ('tiposolicitud', models.CharField(default='Consultar', max_length=40, verbose_name='Tipo de solicitud')),
                ('apicativo', models.CharField(default='kubApp', max_length=40, verbose_name='Aplicativo')),
                ('observaciones', models.CharField(default='', max_length=40, verbose_name='Observaciones')),
            ],
        ),
    ]
