# Generated by Django 5.0.3 on 2024-04-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0009_solicitudsistemasupervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudsistemasupervisor',
            old_name='aplicativo',
            new_name='apicativo',
        ),
    ]
