# Generated by Django 5.0.3 on 2024-07-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0013_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del modulo'),
        ),
    ]
