# Generated by Django 5.0.3 on 2024-08-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0014_alter_modulo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='aplicativo3',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='aplicativo4',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='aplicativo5',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='observaciones3',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='observaciones4',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='observaciones5',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='tiposolicitud3',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='tiposolicitud4',
        ),
        migrations.RemoveField(
            model_name='solicitudsistema',
            name='tiposolicitud5',
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='aplicativo1',
            field=models.CharField(blank=True, choices=[('KUBAPP', 'kubApp'), ('TNS', 'TNS'), ('ALMERA', 'Almera'), ('HICKCENTRAL', 'Hickcentral')], default='kubApp', max_length=40, null=True, verbose_name='Aplicativo 2'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='aplicativo2',
            field=models.CharField(blank=True, choices=[('KUBAPP', 'kubApp'), ('TNS', 'TNS'), ('ALMERA', 'Almera'), ('HICKCENTRAL', 'Hickcentral')], default='kubApp', max_length=40, null=True, verbose_name='Aplicativo 3'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='fechafinalcontrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final del contrato'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='observaciones1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Observaciones 2'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='sede',
            field=models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('UBA PBL', 'UBA Puente barco leones'), ('UBA LIBERTAD', 'UBA Libertad'), ('UBA COMUNEROS', 'UBA Comuneros'), ('UBA AGUA CLARA', 'UBA Agua clara'), ('UBA LOMA DE BOLIVAR', 'UBA Loma de bolivar'), ('UBA POLICLINICO', 'UBA Policlinico')], default='Administrativa', max_length=80, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='tiposolicitud1',
            field=models.CharField(blank=True, default='Consultar', max_length=40, null=True, verbose_name='Tipo de solicitud 2'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='tiposolicitud2',
            field=models.CharField(blank=True, default='Consultar', max_length=40, null=True, verbose_name='Tipo de solicitud 3'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='sede',
            field=models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('UBA PBL', 'UBA Puente barco leones'), ('UBA LIBERTAD', 'UBA Libertad'), ('UBA COMUNEROS', 'UBA Comuneros'), ('UBA AGUA CLARA', 'UBA Agua clara'), ('UBA LOMA DE BOLIVAR', 'UBA Loma de bolivar'), ('UBA POLICLINICO', 'UBA Policlinico')], default='Administrativa', max_length=80, verbose_name='Sede'),
        ),
    ]
