# Generated by Django 5.0.3 on 2024-08-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0017_remove_solicitudsistema_aplicativo1_and_more'),
        ('gestion_supervisor', '0007_alter_supervisor_cargo_alter_supervisor_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsistema',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor'),
        ),
    ]
