# Generated by Django 5.0.3 on 2024-09-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0019_remove_pazysalvo_cedula_pazysalvo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pazysalvo',
            name='rfid',
            field=models.BooleanField(default=False, verbose_name='Tarjeta control de acceso'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='segundoapellido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='segundonombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre'),
        ),
    ]
