# Generated by Django 5.0.3 on 2024-09-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0024_solicitudsistema_ubicacionlaboral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsistema',
            name='tarjetapf',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Tarjeta profesional'),
        ),
    ]
