# Generated by Django 5.0.3 on 2024-09-18 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0025_solicitudsistema_tarjetapf'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsistema',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitudsistema',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
    ]
