# Generated by Django 5.0.3 on 2024-09-18 20:06

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0026_solicitudsistema_fecha_actualizacion_and_more'),
        ('gestion_informes', '0017_alter_informe_totalentregas'),
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsistemasupervisor',
            name='apicativo',
        ),
        migrations.RemoveField(
            model_name='solicitudsistemasupervisor',
            name='observacionessupervisor',
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='aplicativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.aplicativo'),
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='modulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.modulo'),
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='observacionessup',
            field=models.CharField(default=datetime.datetime(2024, 9, 18, 20, 6, 3, 808406, tzinfo=datetime.timezone.utc), max_length=200, verbose_name='Observaciones del supervisor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='tarjetapf',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Tarjeta profesional'),
        ),
        migrations.AddField(
            model_name='solicitudsistemasupervisor',
            name='ubicacionlaboral',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ubicacion laboral'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='dependencia',
            field=models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.dependencia', verbose_name='dependencia'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='fechafinalcontrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final del contrato'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='lugarexpedicion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Lugar de expedicion'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='sede',
            field=models.CharField(blank=True, choices=[('ADMINISTRATIVA', 'Administrativa'), ('UBA PBL', 'UBA Puente barco leones'), ('UBA LIBERTAD', 'UBA Libertad'), ('UBA COMUNEROS', 'UBA Comuneros'), ('UBA AGUA CLARA', 'UBA Agua clara'), ('UBA LOMA DE BOLIVAR', 'UBA Loma de bolivar'), ('UBA POLICLINICO', 'UBA Policlinico')], default='ADMINISTRATIVA', max_length=80, null=True, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='segundoapellido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='segundonombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=40, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='tiposolicitud',
            field=models.CharField(blank=True, choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAS', 'Consultas')], default='Consultar', max_length=40, null=True, verbose_name='Tipo de solicitud'),
        ),
    ]
