# Generated by Django 5.0.3 on 2024-09-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0027_remove_solicitudsistemasupervisor_apicativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='cargo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='observacionessup',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones del supervisor'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='primerapellido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='solicitudsistemasupervisor',
            name='tipodocumento',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula de ciudadania'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cedula de extranjeria')], default='CC', max_length=40, null=True, verbose_name='Tipo de documento'),
        ),
    ]
