# Generated by Django 5.0.3 on 2024-09-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0030_solicitudsistemaadmin'),
        ('gestion_informes', '0017_alter_informe_totalentregas'),
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudsistemarechazado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundonombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre')),
                ('primerapellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer apellido')),
                ('segundoapellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido')),
                ('tipodocumento', models.CharField(blank=True, choices=[('CC', 'Cedula de ciudadania'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cedula de extranjeria')], default='CC', max_length=40, null=True, verbose_name='Tipo de documento')),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('lugarexpedicion', models.CharField(blank=True, max_length=40, null=True, verbose_name='Lugar de expedicion')),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=40, null=True, verbose_name='Sexo')),
                ('telefono', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Telefono')),
                ('celular', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, default='', max_length=40, null=True, verbose_name='Direccion')),
                ('cargo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Cargo')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='Email')),
                ('sede', models.CharField(blank=True, choices=[('ADMINISTRATIVA', 'Administrativa'), ('UBA PBL', 'UBA Puente barco leones'), ('UBA LIBERTAD', 'UBA Libertad'), ('UBA COMUNEROS', 'UBA Comuneros'), ('UBA AGUA CLARA', 'UBA Agua clara'), ('UBA LOMA DE BOLIVAR', 'UBA Loma de bolivar'), ('UBA POLICLINICO', 'UBA Policlinico')], default='ADMINISTRATIVA', max_length=80, null=True, verbose_name='Sede')),
                ('ubicacionlaboral', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ubicacion laboral')),
                ('fechafinalcontrato', models.CharField(blank=True, max_length=90, null=True, verbose_name='Fecha final del contrato')),
                ('tarjetapf', models.CharField(blank=True, max_length=60, null=True, verbose_name='Tarjeta profesional')),
                ('tiposolicitud', models.CharField(blank=True, choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAS', 'Consultas')], default='Consultar', max_length=40, null=True, verbose_name='Tipo de solicitud')),
                ('observaciones', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones')),
                ('observacionessup', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observaciones del supervisor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('aplicativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.aplicativo')),
                ('dependencia', models.ForeignKey(blank=True, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.dependencia', verbose_name='dependencia')),
                ('modulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.modulo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor')),
            ],
        ),
    ]
