# Generated by Django 5.0.3 on 2024-09-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0032_solicitudsistemarechazadoadm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsistemarechazadoadm',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='solicitudsistemarechazadoadm',
            name='usuario',
        ),
    ]
