# Generated by Django 5.0.3 on 2024-09-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0033_remove_solicitudsistemarechazadoadm_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsistema',
            name='aplicativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.aplicativo'),
        ),
    ]
