# Generated by Django 5.0.3 on 2024-10-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0034_alter_solicitudsistema_aplicativo'),
        ('gestion_informes', '0017_alter_informe_totalentregas'),
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
        ('gestion_usuarios', '0076_alter_usolicitudes_email_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsistema',
            name='aplicativo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_identidades.aplicativo'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='dependencia',
            field=models.ForeignKey(default=1, max_length=40, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.dependencia', verbose_name='dependencia'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='sede',
            field=models.CharField(choices=[('ADMINISTRATIVA', 'Administrativa'), ('UBA PBL', 'UBA Puente barco leones'), ('UBA LIBERTAD', 'UBA Libertad'), ('UBA COMUNEROS', 'UBA Comuneros'), ('UBA AGUA CLARA', 'UBA Agua clara'), ('UBA LOMA DE BOLIVAR', 'UBA Loma de bolivar'), ('UBA POLICLINICO', 'UBA Policlinico')], default=1, max_length=80, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor'),
        ),
        migrations.AlterField(
            model_name='solicitudsistema',
            name='tiposolicitud',
            field=models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('CONSULTAS', 'Consultas')], default=1, max_length=40, verbose_name='Tipo de solicitud'),
        ),
        migrations.CreateModel(
            name='pazysalvoaprobado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permisos', models.BooleanField(default=False)),
                ('rfid', models.BooleanField(default=False, verbose_name='Tarjeta control de acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
