# Generated by Django 5.0.3 on 2024-10-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_identidades', '0035_alter_solicitudsistema_aplicativo_and_more'),
        ('gestion_usuarios', '0078_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='pazysalvorechazado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permisos', models.BooleanField(default=False)),
                ('rfid', models.BooleanField(default=False, verbose_name='Tarjeta control de acceso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
