# Generated by Django 4.1.4 on 2023-04-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitud_usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('segundonombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('segundoapellido', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('supervisor', models.CharField(max_length=40)),
                ('tipodocumento', models.CharField(max_length=40)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
