# Generated by Django 4.1.4 on 2023-04-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0002_solicitud_usuario_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('segundonombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('segundoapellido', models.CharField(max_length=40)),
                ('cargo', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('supervisor', models.CharField(max_length=40)),
                ('tipodocumento', models.CharField(max_length=40)),
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('lugarexpedicion', models.CharField(max_length=40)),
                ('dependencia', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=40)),
                ('usuario', models.CharField(max_length=40)),
                ('contrasena', models.CharField(max_length=40)),
                ('rol', models.CharField(max_length=40)),
            ],
        ),
    ]
