# Generated by Django 4.1.4 on 2023-04-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0005_prueba'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitud_usuario',
            table='usolicitud',
        ),
    ]
