# Generated by Django 4.1.4 on 2023-04-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0006_alter_solicitud_usuario_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solicitud_usuario',
            new_name='usolicitudes',
        ),
        migrations.AlterModelTable(
            name='usolicitudes',
            table=None,
        ),
    ]
