# Generated by Django 4.1.4 on 2023-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0007_rename_solicitud_usuario_usolicitudes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('numeroproceso', models.IntegerField(verbose_name='Numero de proceso')),
                ('fechaperfeccionamiento', models.CharField(max_length=300, verbose_name='Fecha de perfeccionamiento')),
                ('objeto', models.CharField(max_length=300, verbose_name='Objeto')),
                ('valor', models.CharField(max_length=300, verbose_name='Valor del contrato')),
                ('fechacontrato', models.CharField(max_length=300, verbose_name='Fecha del contrato')),
                ('fechaterminacion', models.CharField(max_length=300, verbose_name='Fecha de terminacion del contrato')),
                ('duracion', models.CharField(max_length=40, verbose_name='Duracion del contrato')),
            ],
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='cargo',
            field=models.CharField(max_length=40, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='primerapellido',
            field=models.CharField(max_length=40, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='segundoapellido',
            field=models.CharField(max_length=40, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='segundonombre',
            field=models.CharField(max_length=40, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='usolicitudes',
            name='tipodocumento',
            field=models.CharField(max_length=40, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(max_length=40, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=40, verbose_name='Contrasena'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dependencia',
            field=models.CharField(max_length=40, verbose_name='Dependencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lugarexpedicion',
            field=models.CharField(max_length=40, verbose_name='Lugar de expedicion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primerapellido',
            field=models.CharField(max_length=40, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=40, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundoapellido',
            field=models.CharField(max_length=40, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundonombre',
            field=models.CharField(max_length=40, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=40, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='supervisor',
            field=models.CharField(max_length=40, verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipodocumento',
            field=models.CharField(max_length=40, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=40, verbose_name='Usuario'),
        ),
    ]
