# Generated by Django 4.1.4 on 2023-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0008_contrato_alter_usolicitudes_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rp',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero del rp')),
                ('fecha', models.CharField(max_length=300, verbose_name='Fecha del rp')),
                ('duracion', models.CharField(max_length=40, verbose_name='Duracion del contrato')),
                ('valor', models.CharField(max_length=300, verbose_name='Valor del contrato')),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='id',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechaterminacion',
            field=models.CharField(max_length=300, verbose_name='Fecha final del contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero'),
        ),
    ]
