# Generated by Django 4.1.4 on 2023-04-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0010_alter_usuario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(max_length=40, verbose_name='Sexo'),
        ),
    ]
