# Generated by Django 4.1.4 on 2023-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0011_alter_usuario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='actainicio',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero del proceso')),
                ('fecha', models.CharField(max_length=300, verbose_name='Fecha de acta de inicio')),
                ('duracion', models.CharField(max_length=40, verbose_name='Duracion del contrato')),
                ('valor', models.CharField(max_length=300, verbose_name='Valor del contrato')),
            ],
        ),
    ]
