# Generated by Django 4.1.4 on 2023-04-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0012_actainicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prueba',
            old_name='nombre',
            new_name='nombreprueba',
        ),
    ]
