# Generated by Django 4.1.4 on 2023-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0013_rename_nombre_prueba_nombreprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='planilla',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de la planilla')),
                ('fecha', models.CharField(max_length=300, verbose_name='Fecha del pago de la planilla')),
                ('periodo', models.CharField(max_length=40, verbose_name='Periodo de la planilla')),
                ('valortotal', models.CharField(max_length=300, verbose_name='Valor total de la planilla')),
                ('nombrepension', models.CharField(max_length=300, verbose_name='Nombre de la entidad de pension')),
                ('valorpension', models.CharField(max_length=300, verbose_name='Valor de la pension')),
                ('nombresalud', models.CharField(max_length=300, verbose_name='Nombre de la entidad de salud')),
                ('valorsalud', models.CharField(max_length=300, verbose_name='Valor de la salud')),
                ('nombrearl', models.CharField(max_length=300, verbose_name='Nombre de la entidad de arl')),
                ('valorarl', models.CharField(max_length=300, verbose_name='Valor de arl')),
            ],
        ),
    ]
