# Generated by Django 4.1.4 on 2023-04-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0015_actividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='actapago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=300, verbose_name='Objeto del contrato')),
                ('lugar', models.CharField(max_length=40, verbose_name='Lugar donde realizo la actividad')),
                ('valor', models.CharField(max_length=40, verbose_name='Valor del contrato')),
                ('fechaperfeccionamiento', models.CharField(max_length=40, verbose_name='Fecha de perfeccionamiento')),
                ('numeroacta', models.IntegerField(verbose_name='Numero de acta de pago')),
                ('fechacuenta', models.CharField(max_length=600, verbose_name='Fecha en la que pasa la cuenta')),
                ('periodo', models.IntegerField(verbose_name='Periodo de pago')),
            ],
        ),
        migrations.AlterField(
            model_name='actividades',
            name='resultadoactvidades',
            field=models.CharField(max_length=600, verbose_name='Resultado de las actividades'),
        ),
    ]
