# Generated by Django 4.1.4 on 2023-04-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0016_actapago_alter_actividades_resultadoactvidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificadoseguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerocontrato', models.IntegerField(verbose_name='Numero del contrato')),
                ('fechacuenta', models.CharField(max_length=40, verbose_name='Fecha actual de la cuenta')),
                ('objeto', models.CharField(max_length=40, verbose_name='Objeto del contrato')),
                ('rp', models.CharField(max_length=40, verbose_name='Numero del registro presupuestal')),
                ('fechasuscripcion', models.CharField(max_length=40, verbose_name='Fecha de suscripcion de la cuenta')),
                ('fechaterminacion', models.CharField(max_length=40, verbose_name='Fecha de terminacion de la cuenta')),
                ('periodo', models.IntegerField(verbose_name='Periodo de pago')),
                ('numeroplanilla', models.IntegerField(verbose_name='Numero de planilla de pago')),
                ('nombresalud', models.CharField(max_length=40, verbose_name='Nombre de la entidad de salud')),
                ('valorsalud', models.CharField(max_length=40, verbose_name='Valor de la salud')),
                ('nombrepension', models.CharField(max_length=40, verbose_name='Nombre de la entidad de pension')),
                ('valorpension', models.CharField(max_length=40, verbose_name='Valor de la entidad de pension')),
                ('nombrearl', models.CharField(max_length=40, verbose_name='Nombre de la entidad de arl')),
                ('valorarl', models.CharField(max_length=40, verbose_name='Valor de la entidad de arl')),
                ('cuentapago', models.CharField(max_length=40, verbose_name='Nombre de la entidad bancaria')),
                ('numerocuentapago', models.IntegerField(verbose_name='Numero de la entidad bancaria')),
            ],
        ),
    ]
