# Generated by Django 4.1.4 on 2023-04-17 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0022_rp_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actainicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='actapago',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='certificadoseguimiento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
    ]
