# Generated by Django 4.1.4 on 2023-04-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0026_cuentatesoreria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuentapresupuesto',
        ),
        migrations.DeleteModel(
            name='cuentasupervisor',
        ),
        migrations.DeleteModel(
            name='cuentatesoreria',
        ),
    ]
