# Generated by Django 4.1.4 on 2023-04-28 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0027_delete_cuentapresupuesto_delete_cuentasupervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs/', verbose_name='Pdf del contrato'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fecha',
            field=models.CharField(max_length=40, verbose_name='Periodo de actividades'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fechacontrato',
            field=models.CharField(max_length=300, verbose_name='Fecha inicial del  contrato'),
        ),
    ]
