# Generated by Django 4.1.4 on 2023-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0028_contrato_archivo_alter_actividades_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(default=1, upload_to='pdfs/', verbose_name='Pdf del contrato'),
        ),
    ]
