# Generated by Django 4.1.4 on 2023-04-28 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0030_alter_contrato_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdfs/', verbose_name='Pdf del contrato'),
        ),
    ]
