# Generated by Django 4.1.4 on 2023-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0031_alter_contrato_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Pdf del contrato'),
        ),
    ]
