# Generated by Django 4.1.4 on 2023-04-28 15:02

from django.db import migrations, models
import gestion_usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0032_alter_contrato_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(default=gestion_usuarios.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='Pdf del contrato'),
        ),
    ]
