# Generated by Django 4.1.4 on 2023-05-31 22:24

from django.db import migrations, models
import gestion_usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0033_alter_contrato_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentausuario',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='fechaactainicio',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='fechacontrato',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='fechaperfeccionamiento',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='fecharp',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='fechaterminacion',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='numeroactainicio',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='numerorp',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='primerapellido',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='segundoapellido',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='segundonombre',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='tipodocumento',
        ),
        migrations.RemoveField(
            model_name='cuentausuario',
            name='valor',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(default=gestion_usuarios.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='archivo'),
        ),
        migrations.AlterField(
            model_name='cuentausuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cuentausuario',
            name='objeto',
            field=models.CharField(max_length=400, verbose_name='Objeto'),
        ),
    ]
