# Generated by Django 4.1.4 on 2023-05-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0034_remove_cuentausuario_dependencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentausuario',
            name='dependencia',
            field=models.CharField(default='No asignado', max_length=40, verbose_name='Dependencia'),
        ),
        migrations.AddField(
            model_name='cuentausuario',
            name='supervisor',
            field=models.CharField(default='No asignado', max_length=40, verbose_name='Supervisor'),
        ),
    ]
