# Generated by Django 4.1.4 on 2023-06-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0035_cuentausuario_dependencia_cuentausuario_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rp',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
    ]
