# Generated by Django 4.1.4 on 2023-06-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0036_rp_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actainicio',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
    ]
