# Generated by Django 4.1.4 on 2023-06-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0037_actainicio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actapago',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
        migrations.AddField(
            model_name='certificadoseguimiento',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
        migrations.AddField(
            model_name='planilla',
            name='archivo',
            field=models.FileField(default='NO CARGADO', upload_to='pdfs/', verbose_name='archivo'),
        ),
    ]
