# Generated by Django 4.1.4 on 2023-06-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0038_actapago_archivo_actividades_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='', max_length=40, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0, verbose_name='Telefono'),
        ),
    ]
