# Generated by Django 4.1.4 on 2023-06-11 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0039_usuario_direccion_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentabancaria',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero de cuenta bancaria')),
                ('tipocuenta', models.CharField(max_length=40, verbose_name='Tipo de cuenta bancaria')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre de cuenta bancaria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario')),
            ],
        ),
    ]
