# Generated by Django 4.1.4 on 2023-06-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0041_rename_nombre_cuentabancaria_nombrecb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=0, max_length=40, verbose_name='Telefono'),
        ),
    ]
