# Generated by Django 4.1.4 on 2023-06-24 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0047_cuentacontratista_alter_rp_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cuentacontratista',
        ),
    ]
