# Generated by Django 4.1.4 on 2023-06-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0048_delete_cuentacontratista'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentacontratista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroplanilla', models.CharField(default='001', max_length=40, verbose_name='Numero de planilla')),
                ('actividades', models.FileField(default='No', upload_to='pdfs/', verbose_name='actividades')),
            ],
        ),
    ]
