# Generated by Django 4.1.4 on 2023-06-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0050_remove_cuentacontratista_actividades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_usuarios.usuario'),
        ),
    ]
