# Generated by Django 4.1.4 on 2023-06-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0051_cuentacontratista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontratista',
            name='usuario',
        ),
    ]
