# Generated by Django 4.1.4 on 2023-06-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0054_cuentacontratista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontratista',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cuentacontratista',
            name='cedula',
            field=models.IntegerField(default=1, verbose_name='Cedula'),
        ),
    ]
