# Generated by Django 4.1.4 on 2023-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0055_remove_cuentacontratista_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='nombrecompleto',
            field=models.CharField(default='No asignado', max_length=80, verbose_name='Nombre completo'),
        ),
    ]
