# Generated by Django 4.1.4 on 2023-06-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0056_cuentacontratista_nombrecompleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='objetocontrato',
            field=models.CharField(default='No asignado', max_length=200, verbose_name='Objeto del contrato'),
        ),
    ]
