# Generated by Django 4.1.4 on 2023-06-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0058_cuentacontratista_pdfcontrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='pdfactividades',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=80, verbose_name='Pdf de actividades'),
        ),
    ]
