# Generated by Django 4.1.4 on 2023-06-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0059_cuentacontratista_pdfactividades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentacontratista',
            name='pdfactividades',
        ),
    ]
