# Generated by Django 4.1.4 on 2023-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0060_remove_cuentacontratista_pdfactividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='pdfplanilla',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf de la planilla'),
        ),
        migrations.AlterField(
            model_name='cuentacontratista',
            name='pdfcontrato',
            field=models.CharField(default='pdfs/NOCARGADO', max_length=200, verbose_name='Pdf del contrato'),
        ),
    ]
