# Generated by Django 4.1.4 on 2023-06-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0061_cuentacontratista_pdfplanilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=40, verbose_name='Telefono'),
        ),
    ]
