# Generated by Django 4.1.4 on 2023-07-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0062_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontratista',
            name='flujo',
            field=models.CharField(default='Pendiente de pasar cuenta', max_length=80, verbose_name='Flujo'),
        ),
    ]
