# Generated by Django 4.1.4 on 2023-07-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0064_alter_usuario_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='supervisor',
            field=models.CharField(default='No asignado', max_length=40, verbose_name='Supervisor'),
        ),
    ]
