# Generated by Django 5.0.3 on 2024-03-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0065_alter_usuario_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usolicitudes',
            name='modulo',
            field=models.CharField(choices=[('identidades', 'Gestion de identidades'), ('cuentas', 'Gestion de cuentas'), ('interoapibilidad', 'Gestion de interoapibilidad'), ('bitacora', 'Gestion de bitacora')], default='identidades', max_length=40, verbose_name='Sistema'),
        ),
    ]
