# Generated by Django 5.0.3 on 2024-03-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0066_usolicitudes_modulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usolicitudes',
            name='modulo',
        ),
    ]
