# Generated by Django 5.0.3 on 2024-07-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0007_alter_supervisor_cargo_alter_supervisor_cedula_and_more'),
        ('gestion_usuarios', '0067_remove_usolicitudes_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usolicitudes',
            name='supervisor',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor', verbose_name='supervisor'),
        ),
    ]
