# Generated by Django 5.0.3 on 2024-09-30 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
        ('gestion_usuarios', '0070_alter_usuario_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudrechazada',
            fields=[
                ('nombre', models.CharField(max_length=40, verbose_name='Primer nombre')),
                ('segundonombre', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo nombre')),
                ('primerapellido', models.CharField(max_length=40, verbose_name='Primer apellido')),
                ('segundoapellido', models.CharField(blank=True, max_length=40, null=True, verbose_name='Segundo apellido')),
                ('cargo', models.CharField(max_length=40, verbose_name='Cargo')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('tipodocumento', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Cedula de extranjeria')], default='CC', max_length=40, verbose_name='Tipo de documento')),
                ('cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('supervisor', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor', verbose_name='supervisor')),
            ],
        ),
    ]
