# Generated by Django 5.0.3 on 2024-10-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
        ('gestion_usuarios', '0072_alter_usuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contrasena',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='supervisor',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_detail', to='gestion_supervisor.supervisor', verbose_name='supervisor'),
        ),
    ]
