# Generated by Django 5.0.3 on 2024-10-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0073_remove_usuario_contrasena_alter_usuario_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_identidadades', 'Administrador de identidades'), ('supervisor', 'Supervisor'), ('identidades', 'Usuario final de identidades'), ('informes', 'informes'), ('super_admin_identidades', 'Super admin de identidades'), ('admin_sara', 'Administrador de SARA')], default='CONTRATISTA', max_length=40, verbose_name='Rol'),
        ),
    ]
