# Generated by Django 5.0.3 on 2024-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0075_alter_usuario_cargo_alter_usuario_dependencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usolicitudes',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Correo personal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=40, null=True, verbose_name='Correo personal'),
        ),
    ]
