# Generated by Django 5.0.3 on 2024-10-07 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_supervisor', '0010_alter_supervisor_usuario'),
        ('gestion_usuarios', '0076_alter_usolicitudes_email_alter_usuario_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usolicitudes',
            name='supervisor',
            field=models.ForeignKey(default=1, max_length=40, on_delete=django.db.models.deletion.CASCADE, to='gestion_supervisor.supervisor', verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario autenticado'),
        ),
    ]
