# Generated by Django 5.0.3 on 2024-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0077_alter_usolicitudes_supervisor_alter_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin_identidadades', 'Administrador de identidades'), ('supervisor', 'Supervisor'), ('identidades', 'Usuario final de identidades'), ('informes', 'ente de control (informes)'), ('admin_sara', 'Administrador de SARA')], default='identidades', max_length=40, verbose_name='Rol'),
        ),
    ]
