# Generated by Django 5.0.3 on 2024-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_usuarios', '0078_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fechafinalcontrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha final del contrato'),
        ),
    ]
