# Generated by Django 5.0.3 on 2024-03-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entecontrol',
            old_name='estado',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='entecontrol',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre ente de control'),
        ),
    ]
