# Generated by Django 5.0.3 on 2024-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0002_rename_estado_entecontrol_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entecontrol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Descripcion ente de control'),
        ),
    ]
