# Generated by Django 5.0.3 on 2024-03-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0003_alter_entecontrol_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre dependencia')),
                ('responsable', models.CharField(max_length=200, verbose_name='Nombre del responsable')),
                ('correoresponsable', models.CharField(max_length=200, verbose_name='Correo del responsable')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
