# Generated by Django 5.0.3 on 2024-03-30 17:03

import django.db.models.deletion
import gestion_informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0004_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del informe')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Nombre del informe')),
                ('normativa', models.FileField(default=gestion_informes.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='Normativa')),
                ('fechaentregainicial', models.CharField(max_length=200, verbose_name='Fecha inicial de entrega')),
                ('fechaentregapendiente', models.CharField(max_length=200, verbose_name='Fecha pendiente de entrega')),
                ('periodicidad', models.CharField(max_length=200, verbose_name='Periodicidad cantidad')),
                ('periodicidadtipo', models.CharField(max_length=200, verbose_name='Tipo de periodicidad')),
                ('totalentregas', models.IntegerField(verbose_name='Total de entregas')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.dependencia')),
                ('entecontrol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.entecontrol')),
            ],
        ),
    ]
