# Generated by Django 5.0.3 on 2024-03-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0005_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='descripcion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcion del informe'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug del informe'),
        ),
    ]
