# Generated by Django 5.0.3 on 2024-03-30 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0006_informe_descripcion_alter_informe_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='alarma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField(verbose_name='Dias de anticipacion a la fecha de entrega')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.informe')),
            ],
        ),
    ]
