# Generated by Django 5.0.3 on 2024-04-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0007_alarma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarma',
            name='dias',
            field=models.IntegerField(verbose_name='Dias de anticipacion alarma'),
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=200, verbose_name='Fecha')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_informes.informe')),
            ],
        ),
    ]
