# Generated by Django 5.0.3 on 2024-04-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0009_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='slug',
        ),
    ]
