# Generated by Django 5.0.3 on 2024-04-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0010_remove_informe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='fechaentregainicial',
            field=models.DateField(verbose_name='Fecha inicial de entrega'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='fechaentregapendiente',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha pendiente de entrega'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='periodicidad',
            field=models.IntegerField(verbose_name='Periodicidad cantidad'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='periodicidadtipo',
            field=models.CharField(choices=[('Dias', 'Días'), ('Meses', 'Meses')], default='Dias', max_length=200, verbose_name='Tipo de periodicidad'),
        ),
    ]
