# Generated by Django 5.0.3 on 2024-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0013_informe_alarmas_alter_informe_periodicidadtipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='alarmas2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Segunda alarma'),
        ),
        migrations.AddField(
            model_name='informe',
            name='alarmas3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tercera alarma'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
    ]
