# Generated by Django 5.0.3 on 2024-05-18 14:43

import gestion_informes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0014_informe_alarmas2_informe_alarmas3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(default=gestion_informes.models.obtener_archivo_predeterminado, upload_to='pdfs/', verbose_name='Archivo de evidencia'),
        ),
    ]
