# Generated by Django 5.0.3 on 2024-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0015_evidencia_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
