# Generated by Django 5.0.3 on 2024-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_informes', '0016_alter_evidencia_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='totalentregas',
            field=models.IntegerField(blank=True, default='1000', null=True, verbose_name='Total de entregas'),
        ),
    ]
